global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'policy-service'
    scrape_interval: 15s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['policy-app:8080']