ALTER TABLE policies ADD COLUMN created_at TIMESTAMP;
ALTER TABLE policies ADD COLUMN updated_at TIMESTAMP;
ALTER TABLE policies ADD COLUMN created_by VARCHAR(255);

ALTER TABLE users ADD COLUMN created_at TIMESTAMP;
ALTER TABLE users ADD COLUMN updated_at TIMESTAMP;
ALTER TABLE users ADD COLUMN created_by VARCHAR(255);
